version: "3.8"
services:
  postgres:
    image: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: "postgres -c max_connections=200 -c wal_level=logical"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: notes_development
      RAILS_ENV: development
      AUTH_USER_NAME: demo
      AUTH_USER_PASS: demo
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
